# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Internal functions written in C++ to speed up maximization process of the censored bivariate probit model with random intercepts
#'
#' Functions that calculate the modes of the random intercepts and that contain the loops for computing the log likelihood approximated by GHQ.
#' 
#' @keywords internal
mode <- function(par, x, yS, yO, linpredS, linpredO, group_aux, rho, tau, sigma1, sigma2) {
    .Call(`_selMNAR_MI_mode`, par, x, yS, yO, linpredS, linpredO, group_aux, rho, tau, sigma1, sigma2)
}

#' @rdname mode
#' @keywords internal
loop1 <- function(yS, yO, linpredS, linpredO, rho, tau, sigma1, sigma2, w1, a1, group_aux, group, M, chol_vc_re) {
    .Call(`_selMNAR_MI_loop1`, yS, yO, linpredS, linpredO, rho, tau, sigma1, sigma2, w1, a1, group_aux, group, M, chol_vc_re)
}

#' Internal functions written in C++ to speed up maximization process of the ordered probit model with sample selection and random intercepts
#'
#' Functions that calculate the modes of the random intercepts and that contain the loops for computing the log likelihood approximated by GHQ.
#' 
#' @keywords internal
mode_ord <- function(par, x, yS, yO, linpredS, linpredO, group_aux, rho, tau, z, sigma1, sigma2, levels) {
    .Call(`_selMNAR_MI_mode_ord`, par, x, yS, yO, linpredS, linpredO, group_aux, rho, tau, z, sigma1, sigma2, levels)
}

#' @rdname mode_ord
#' @keywords internal
loop1_ord <- function(yS, yO, linpredS, linpredO, rho, tau, sigma1, sigma2, z, levels, w1, a1, group_aux, group, M, chol_vc_re) {
    .Call(`_selMNAR_MI_loop1_ord`, yS, yO, linpredS, linpredO, rho, tau, sigma1, sigma2, z, levels, w1, a1, group_aux, group, M, chol_vc_re)
}

